REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM driver;
DROP USER driver;
CREATE ROLE driver WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'driver';

GRANT ALL PRIVILEGES ON Passrecords TO driver;
GRANT SELECT ON Accounts TO driver;
GRANT SELECT ON Person TO driver;
