REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM unverif;
DROP USER unverif;
CREATE ROLE unverif WITH
	LOGIN
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	NOINHERIT
	NOREPLICATION
	CONNECTION LIMIT -1
	PASSWORD 'unverif';

GRANT ALL PRIVILEGES ON Passrecords TO unverif;
GRANT SELECT ON Accounts TO unverif;
GRANT SELECT ON Person TO unverif;
